version: 2

sources:
  - name: raw_weather
    database: "datazoomcamp-490302"
    schema: raw_weather          # your BigQuery dataset name
    tables:
      - name: daily_weather       # your raw table from dlt
    
  - name: kenya_weather
    database: "datazoomcamp-490302"
    schema: kenya_weather        # your BigQuery dataset name
    tables:
      - name: dim_counties        # your raw table from dlt
      - name: weather_daily        # your raw table from dlt

models:
  - name: stg_daily_weather
    columns:
      - name: weather_date
        tests:
          - not_null
      - name: county
        tests:
          - not_null
      - name: rainfall_mm
        tests:
          - not_null

  - name: stg_counties
    columns:
      - name: county
        tests:
          - not_null
          - unique
      - name: agro_zone
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_agro_zones')
                field: agro_zone